services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - NODE_ENV=production
      - DB_CONNECTION_URL=postgres://myappuser:n0nS3cure@db:5432/MyAppDB
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "pnpm install && pnpm build && pnpm migrations && pnpm start"]

  db:
    image: postgres:17.6-alpine3.22
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=n0nS3cure
      - POSTGRES_DB=MyAppDB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myappuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

volumes:
  pgdata: